name: Hotel QR APP Cloud Deployment

on:
  push:
    branches:
      - main 
  workflow_dispatch:

concurrency: 
  group: production
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  BACKEND_REPO: hotel-qr-backend
  FRONTEND_REPO: hotel-qr-frontend
  ECS_CLUSTER: hotel-qr-cluster
  BACKEND_SERVICE: hotel-qr-backend-svc
  FRONTEND_SERVICE: hotel-qr-frontend-svc

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
  
        env: 
          TF_VAR_registrar_api_key: ${{ secrets.DIGITALPLAT_API_KEY }}

  
  build-and-push:
    name: Build & Push Docker Images
    needs: terraform 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Backend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG -t $ECR_REGISTRY/$BACKEND_REPO:latest .
          docker push $ECR_REGISTRY/$BACKEND_REPO --all-tags

      - name: Build, tag, and push Frontend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build --build-arg NEXT_PUBLIC_API_URL="https://devopsnawy.qzz.io" -t $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG -t $ECR_REGISTRY/$FRONTEND_REPO:latest .
          docker push $ECR_REGISTRY/$FRONTEND_REPO --all-tags

      - name: Force new ECS deployment for Backend
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $BACKEND_SERVICE --force-new-deployment

      - name: Force new ECS deployment for Frontend
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $FRONTEND_SERVICE --force-new-deployment
